import type { Metadata } from 'next'
import '../styles/globals.css'
import '../styles/reset.css'

export const metadata: Metadata = {
  title: 'Akademia Debat Profilaktycznych',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pl">
      <body>
        {children}
      </body>
    </html>
  )
}
